language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - amadoucd@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
- chmod +x mvnw
- gem install travis
- sudo mkdir -p /usr/local/bin/ecs-cli
- pip install --user awscli
- curl https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest | /usr/local/bin/ecs-cli
- export PATH=$PATH:$HOME/.local/bin
- export BUILD_NAME=test123456
- export IMAGE_NAME=acdd1234/transaction
env:
  global:
  - secure: mBgpG9/WRZ8xe4c2Am+1AWUHC1rIi5YH4yr/FaI7wC3WGb9VfQV+3At5SBgg/7sIrC2AJuiEUTgpVB+fSLVR6ggBJTDb8ctTSE7s88OJDJ5SV5q/qD8LB0AKPc7jz1nyOYXfuyVtVzvViUs8XFUsefLIMetiMW81yvg/KBA80RkcP6f5+1TKJnqHfQtvPAZ/21ac5FG4kO4sTN/qlNBlZGPuiBH6QtcPkaQZD36iujr+9dy851Hv5Hz/yR90zNavT38yJbzfLQ/nu+qxMcLp1hLTbL4T0EIY4dPPKt0FMHPqmb2NKFf62SUnmBFk8UvMM9kbGs+wf/7wr7v8gmzMXXP97RvkHuZJX7TgdmNpO4dZjCxtoiqi77UDTaPGrsdd4TqNxiUQ6GhVE2NCksIaJHwduNDqbH7W4EfXVxVHIcQnJ2J8CifFeE04uCwIQMcdtQyo9OqhVHrHP+5ZyNT8fLAN2s8NZlYZp5VMH6Y5rDqXV16dGdUE49TA/wSLzD6xfhU1bZu8KZabzPWwPCQRCMzHz6atcqPJ8HeAWJpMBYd84y6lOVgB4GoOUbs4KP7F4irpD16HYs4qPdi+9xCSmsJIhtclXC4vaevNuZNENJyMu4hG1CfljO1RkypIdleatK3noMU5dMMVjv0CaKYbb+JA8i17z4mZ+IGYmftYnNk=
  - secure: VnX2R2L9OK4Av2kbSdqRA2vnSL6vCGZb2i0xCahDNawmYPEY99Yl5tpH8i6Pr88LfGkYqfPWSWLt3s2DFatg6TqXi4ymU9vQJwwi4r7JN6t9N7RFrncQ2483nWqFYGqDOkkDRaWZxsRGQClYwQPg2LBPI5vp6SUaQJ9jV7I7zN8xHOFQKFu3Al0OmgoYi1IPFJzkGjms3sfdKiEW3hBU6GnqNl+PgHJj6WweVBMsMB+DeVjmGgSTrPbPHS7hH+o/+QIDjxEJTVkMuzR/cqK0BVBmbTpwWK/F3udlvj5VaebtG8r60ZEOjwWo40s04if09WRNAlyGb1ouOlRuF0Kh5O/MNfvoM1XPLW9ynJYnkxzQOTsDtvl8tukilFG/t1t5hIA+fjSAbXkJTYqis7KgG+9N+lS6k9YY4iRklDuO+9DywnyEUtJAIwOdKs8vccCANwhZ6d759vuOdfEL6lNUlmYA6rOXWL54/HcXchWZUzmAGLIJ5Vgaoe54ujw9Be1wSuoaooEEUXjuEX9a24Z35Nleui5M3UhOQhewVtWHqI4o/ednEas4L0yf6oY7svZnucc4ixlOfeZA3nYAggjTq06fU9BIqV1Pgr/6ORTKY+rmlkULr9nvdKeyTvvbvtMf27wHWr+Icj2leCHch3iu2wzlL93dhuxe3cxkL2SC/FQ=
  - secure: mTaRSKlFYahk4EUcPLoi+AtIwT0NJUS827IpC2FkLSYkAr13TP1niNoP0gE430cnvKf6LWDUV5DKE19L7dwQG616Z62P8uOaU+uYMW1BKpMshxOsrbJWsrjLZeEQ4/sjhBXGPsZNH8EGKSTEoZN3FN7jz2u5Fmq6Dnchf9uLdFvSQCW/7xTw7PAPM/rumpQD/mFz2yb4P+QuTXHk1AyarstpNrHVYQxsaq70AH1BTXA1VNPIeS5ZZyFg5isfNDy89afV3NYz2d9BqZGfWn7sv7wKybKo2caI4hrT+AOgidJCy6VOt+ZEeT1cymL8WSbmae6iigOKuFmSnSmOA95mGkq9t0p2D7DLYwRt91fQvM8nVgbncj4H7g93ECulIHm5IxyzM3i0/BX1YQHl9Dq6wHVBTQX/LEz//pP0VZK+TO80gQGFtNEgS1j4ZcGHd5GR+RO37MNFZFMmX95fui0iv89Q+rr5VOmdeL2hlzEgAYKsp2KMFH/qVzrKJ0Z8rD83tlwz4DgdCE99fSNCTvg8qPRA4UBc2kHfotjmxyyvNa9KDwNERdFdCCkJRjKUXwVdPY3YGCwy6FXooXp3hrbbxfG07mV3aYbzKNlgewPg8qLpMDL7+DKiNSxyMeyL3kiZ7y5/I0XTWivYh/UniaR94BIV7ljzJVd7su34LjSw/vc=
  - secure: opqZdYGKImBSlU77I2OSK7dBDQkwnLcF59GjGmowdpNOKVFPVNSHI4h/NOVtVq15hl/6yVApakhg74e7TiHTF7WbDce+qg+fFJjUquZjBNaXIyX7B9C7OQoBPwqDc0PEwPeDEpGx0YqAPzJqv/NH1ejwm6EDxkXytRMQflwfFSouNKXbNiPD3EhCPz6f8jLRyRr+ApZy8U1keIUTN2/ad9o2cKtiTvHUlBwjzXkDCVak9P+4ErCHg7Ojd4t6Lq4Lwedjr991WQQco/2cWFmwy09LU6Iw9Mk8mtP9o6j9+KReiRGKxrqW5i7/R+vQtHP/rrkqdMFjK7S8ZIrtvpnuF0VjubjPQD8oxqGeLpeKrPLpXHlO3pn24KQe5aVMa7qzkTTx7aG8OrhGwOn4x6LV4wSjldx0mP92ObMOVSLWL/GVSnSrGig2OsXlXlCmdibXkFtEbn5m1W9LTo1DQP1763wgVnpioc/5G2i1Z/nlU4wF7em9As4GdZjQyn7GsmMfRcCkIeBjhg8blWN8OzjlFtJOM77QU07b/VtP8NQcnSTkprgtyU9hukAU6QClLUTV+Kmp8G139HTwpGtSxTjL6mqWls1FsnEo3Wc/jazRze6HQYPqEHZ0tAcmCcYhW+S5sDKtf0xh67M6hqcRnuG8L7LX3tksYMgvC6xov9hs+4I=
after_success:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker build -t $IMAGE_NAME:$BUILD_NAME .
- docker tag $MAGE_NAME:$BUILD_NAME $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
- ecs-cli configure --region us-east-1 --access-key $AWS_ACCESS_KEY --secret-key $AWS_SECRET_KEY --cluster transactioncicd
- ecs-cli compose --file docker/common/docker-compose.yml up


