language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - amadoucd@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
  - chmod +x mvnw
  - gem install travis
  - curl -o /user/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
  - export BUILD_NAME=test12345
  - export IMAGE_NAME=acdd1234/transaction
env:
  global:
  - secure: mBgpG9/WRZ8xe4c2Am+1AWUHC1rIi5YH4yr/FaI7wC3WGb9VfQV+3At5SBgg/7sIrC2AJuiEUTgpVB+fSLVR6ggBJTDb8ctTSE7s88OJDJ5SV5q/qD8LB0AKPc7jz1nyOYXfuyVtVzvViUs8XFUsefLIMetiMW81yvg/KBA80RkcP6f5+1TKJnqHfQtvPAZ/21ac5FG4kO4sTN/qlNBlZGPuiBH6QtcPkaQZD36iujr+9dy851Hv5Hz/yR90zNavT38yJbzfLQ/nu+qxMcLp1hLTbL4T0EIY4dPPKt0FMHPqmb2NKFf62SUnmBFk8UvMM9kbGs+wf/7wr7v8gmzMXXP97RvkHuZJX7TgdmNpO4dZjCxtoiqi77UDTaPGrsdd4TqNxiUQ6GhVE2NCksIaJHwduNDqbH7W4EfXVxVHIcQnJ2J8CifFeE04uCwIQMcdtQyo9OqhVHrHP+5ZyNT8fLAN2s8NZlYZp5VMH6Y5rDqXV16dGdUE49TA/wSLzD6xfhU1bZu8KZabzPWwPCQRCMzHz6atcqPJ8HeAWJpMBYd84y6lOVgB4GoOUbs4KP7F4irpD16HYs4qPdi+9xCSmsJIhtclXC4vaevNuZNENJyMu4hG1CfljO1RkypIdleatK3noMU5dMMVjv0CaKYbb+JA8i17z4mZ+IGYmftYnNk=
  - secure: VnX2R2L9OK4Av2kbSdqRA2vnSL6vCGZb2i0xCahDNawmYPEY99Yl5tpH8i6Pr88LfGkYqfPWSWLt3s2DFatg6TqXi4ymU9vQJwwi4r7JN6t9N7RFrncQ2483nWqFYGqDOkkDRaWZxsRGQClYwQPg2LBPI5vp6SUaQJ9jV7I7zN8xHOFQKFu3Al0OmgoYi1IPFJzkGjms3sfdKiEW3hBU6GnqNl+PgHJj6WweVBMsMB+DeVjmGgSTrPbPHS7hH+o/+QIDjxEJTVkMuzR/cqK0BVBmbTpwWK/F3udlvj5VaebtG8r60ZEOjwWo40s04if09WRNAlyGb1ouOlRuF0Kh5O/MNfvoM1XPLW9ynJYnkxzQOTsDtvl8tukilFG/t1t5hIA+fjSAbXkJTYqis7KgG+9N+lS6k9YY4iRklDuO+9DywnyEUtJAIwOdKs8vccCANwhZ6d759vuOdfEL6lNUlmYA6rOXWL54/HcXchWZUzmAGLIJ5Vgaoe54ujw9Be1wSuoaooEEUXjuEX9a24Z35Nleui5M3UhOQhewVtWHqI4o/ednEas4L0yf6oY7svZnucc4ixlOfeZA3nYAggjTq06fU9BIqV1Pgr/6ORTKY+rmlkULr9nvdKeyTvvbvtMf27wHWr+Icj2leCHch3iu2wzlL93dhuxe3cxkL2SC/FQ=
after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t $IMAGE_NAME:$BUILD_NAME .
  - docker tag $MAGE_NAME:$BUILD_NAME $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME