language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - amadoucd@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
  - chmod +x mvnw
  
  
  
  